from __future__ import annotations

import enum
import html
import hashlib
import json
import secrets
from dataclasses import dataclass, field
from datetime import datetime
from uuid import UUID


class ReportType(enum.Enum):
    EXECUTIVE = "executive"
    TECHNICAL = "technical"
    ATTACK_PATH = "attack_path"
    COVERAGE = "coverage"
    EVIDENCE_INDEX = "evidence_index"
    CLEANUP = "cleanup"
    RETEST = "retest"


class ExportFormat(enum.Enum):
    HTML = "html"
    JSON = "json"
    SARIF = "sarif"
    CSV = "csv"
    MARKDOWN = "markdown"
    PDF = "pdf"


@dataclass(frozen=True)
class ReportManifest:
    engagement_revision_id: UUID
    coverage_watermark: datetime
    finding_versions: dict[str, int]
    attack_path_ids: list[str]
    evidence_digests: list[str]
    template_digest: str
    risk_model_version: str
    renderer_digest: str

    def compute_digest(self) -> str:
        canonical = json.dumps(
            {
                "engagement_revision_id": str(self.engagement_revision_id),
                "coverage_watermark": self.coverage_watermark.isoformat(),
                "finding_versions": self.finding_versions,
                "attack_path_ids": sorted(self.attack_path_ids),
                "evidence_digests": sorted(self.evidence_digests),
                "template_digest": self.template_digest,
                "risk_model_version": self.risk_model_version,
                "renderer_digest": self.renderer_digest,
            },
            sort_keys=True,
            separators=(",", ":"),
        )
        return f"sha256:{hashlib.sha256(canonical.encode()).hexdigest()}"


REPORT_TEMPLATE_VERSION = "1.0.0"
RISK_MODEL_VERSION = "arsgoatia-chain-severity/1.0.0"


def render_finding_html(
    finding: dict,
    evidence: list[dict],
    nonce: str | None = None,
) -> str:
    if nonce is None:
        nonce = secrets.token_urlsafe(16)
    esc = html.escape

    evidence_rows = ""
    for ev in evidence:
        evidence_rows += (
            f"<tr><td>{esc(str(ev.get('kind', '')))}</td>"
            f"<td><code>{esc(str(ev.get('digest', '')))}</code></td>"
            f"<td>{esc(str(ev.get('sensitivity', '')))}</td></tr>\n"
        )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'nonce-{nonce}'; script-src 'nonce-{nonce}';">
<title>ArsGoatia Finding: {esc(str(finding.get('weakness', 'Unknown')))}</title>
<style nonce="{nonce}">
:root {{--bg:#0d1117;--fg:#c9d1d9;--accent:#58a6ff;--border:#30363d;--warn:#f85149;--ok:#3fb950}}
*{{margin:0;padding:0;box-sizing:border-box}}
body{{font-family:system-ui,-apple-system,sans-serif;background:var(--bg);color:var(--fg);padding:2rem;max-width:900px;margin:0 auto}}
h1{{color:var(--accent);margin-bottom:1rem;font-size:1.5rem}}
h2{{color:var(--fg);margin:1.5rem 0 .5rem;font-size:1.2rem;border-bottom:1px solid var(--border);padding-bottom:.25rem}}
table{{width:100%;border-collapse:collapse;margin:.5rem 0}}
th,td{{text-align:left;padding:.5rem;border:1px solid var(--border)}}
th{{background:#161b22;font-weight:600}}
code{{background:#161b22;padding:.1rem .3rem;border-radius:3px;font-size:.85em}}
.severity-critical{{color:var(--warn);font-weight:700}}
.severity-high{{color:#f0883e;font-weight:700}}
.badge{{display:inline-block;padding:.2rem .6rem;border-radius:3px;font-size:.8rem;font-weight:600}}
.badge-confirmed{{background:#238636;color:#fff}}
.badge-candidate{{background:#6e7681;color:#fff}}
.footer{{margin-top:2rem;padding-top:1rem;border-top:1px solid var(--border);font-size:.8rem;color:#8b949e}}
</style>
</head>
<body>
<h1>ArsGoatia Finding Report</h1>
<h2>Finding: {esc(str(finding.get('weakness', '')))}</h2>
<table>
<tr><th>Status</th><td><span class="badge badge-{esc(str(finding.get('status', 'candidate')))}">{esc(str(finding.get('status', '')))}</span></td></tr>
<tr><th>Affected Object</th><td>{esc(str(finding.get('affected_object', '')))}</td></tr>
<tr><th>Confidence</th><td>{esc(str(finding.get('confidence', '')))}</td></tr>
<tr><th>Severity</th><td>{esc(str(finding.get('severity', '')))}</td></tr>
<tr><th>Root Cause</th><td>{esc(str(finding.get('root_cause', '')))}</td></tr>
<tr><th>Validator</th><td><code>{esc(str(finding.get('validator_digest', '')))}</code></td></tr>
</table>

<h2>Evidence</h2>
<table>
<tr><th>Kind</th><th>Digest</th><th>Sensitivity</th></tr>
{evidence_rows}
</table>

<div class="footer">
Generated by ArsGoatia | Template v{REPORT_TEMPLATE_VERSION} | Risk model: {RISK_MODEL_VERSION}<br>
This report is a frozen snapshot. Regeneration from the same manifest produces identical output.
</div>

<script nonce="{nonce}">
document.addEventListener('keydown',e=>{{if((e.ctrlKey||e.metaKey)&&e.key==='p'){{e.preventDefault();window.print();}}}});
</script>
</body>
</html>"""


def render_sarif(findings: list[dict], tool_version: str = "0.1.0") -> dict:
    results = []
    for f in findings:
        results.append({
            "ruleId": f.get("weakness", "unknown"),
            "level": "error" if f.get("status") == "confirmed" else "warning",
            "message": {"text": f.get("root_cause", "No root cause provided")},
            "locations": [
                {
                    "physicalLocation": {
                        "artifactLocation": {"uri": f.get("affected_object", "unknown")},
                    }
                }
            ],
            "properties": {
                "confidence": f.get("confidence"),
                "severity": f.get("severity"),
                "evidenceDigests": f.get("evidence_digests", []),
            },
        })

    return {
        "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/main/sarif-2.1/schema/sarif-schema-2.1.0.json",
        "version": "2.1.0",
        "runs": [
            {
                "tool": {
                    "driver": {
                        "name": "ArsGoatia",
                        "version": tool_version,
                        "informationUri": "https://github.com/eBruno-Sec/MISC/tree/main/arsgoatia",
                        "rules": [],
                    }
                },
                "results": results,
            }
        ],
    }
