"""Self-contained HTML reports (§28), reusing the olympus apollo.py patterns:
dark theme, every interpolated value html.escape'd, a per-report CSP nonce, and a
client-side export script. Reproduction blocks reuse the ported poc redaction so
no artifact leaks a token.
"""

from __future__ import annotations

import html as _html
import secrets

from evidence.poc import to_curl, to_raw_http

_STYLE = """
:root { color-scheme: dark; }
* { box-sizing: border-box; }
body { margin:0; font:15px/1.6 ui-sans-serif,system-ui,sans-serif; background:#0b0e14; color:#d7dce5; }
.wrap { max-width: 900px; margin: 0 auto; padding: 2rem; }
h1 { font-size:1.5rem; color:#e8edf5; margin:0 0 .25rem; }
h2 { font-size:1.05rem; color:#9ecbff; border-bottom:1px solid #1c2230; padding-bottom:.3rem; margin-top:2rem; }
.sev { display:inline-block; padding:.15rem .6rem; border-radius:6px; font-weight:600; font-size:.8rem; }
.sev.critical{background:#5b1620;color:#ffb3bd}.sev.high{background:#5a2a10;color:#ffcf9e}
.sev.medium{background:#4a3c12;color:#ffe39e}.sev.low{background:#123a2a;color:#9ff0c8}
.sev.informational{background:#1c2230;color:#9ecbff}
pre { background:#151a24; padding:1rem; border-radius:8px; overflow:auto; font-size:13px; }
code { color:#9ecbff; }
table { width:100%; border-collapse:collapse; } td,th { text-align:left; padding:.4rem .6rem; border-bottom:1px solid #1c2230; }
.muted { color:#7c8aa5; font-size:.85rem; }
button { background:#1c2230; color:#d7dce5; border:1px solid #2a3346; border-radius:6px; padding:.4rem .8rem; cursor:pointer; }
"""

_EXPORT_SCRIPT = """
document.querySelectorAll('[data-export]').forEach(b=>b.addEventListener('click',()=>{
  const blob=new Blob([document.documentElement.outerHTML],{type:'text/html'});
  const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='report.html';a.click();
}));
"""


def _esc(v) -> str:
    return _html.escape(str(v if v is not None else ""))


def _shell(title: str, body: str) -> str:
    nonce = secrets.token_urlsafe(16)
    return (
        "<!doctype html><html lang='en'><head><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width, initial-scale=1'>"
        f"<meta http-equiv='Content-Security-Policy' content=\"default-src 'none'; "
        f"style-src 'nonce-{nonce}'; script-src 'nonce-{nonce}'\">"
        f"<title>{_esc(title)}</title><style nonce='{nonce}'>{_STYLE}</style></head>"
        f"<body><div class='wrap'>{body}"
        f"<p class='muted'>Generated by ArsGoatia. Authorized assessment only.</p>"
        f"</div><script nonce='{nonce}'>{_EXPORT_SCRIPT}</script></body></html>"
    )


def atomic_finding_html(finding: dict, evidence: list[dict] | None = None,
                        exchanges: list[dict] | None = None) -> str:
    sev = _esc(finding.get("severity_label", "informational"))
    repro = ""
    for ex in exchanges or []:
        repro += f"<pre><code>{_esc(to_curl(ex))}</code></pre>"
        repro += f"<pre><code>{_esc(to_raw_http(ex))}</code></pre>"
    ev_rows = "".join(
        f"<tr><td>{_esc(e.get('evidence_type'))}</td><td><code>{_esc(e.get('sha256'))}</code></td>"
        f"<td>{_esc(e.get('object_uri'))}</td></tr>"
        for e in (evidence or [])
    )
    body = (
        f"<h1>{_esc(finding.get('title'))}</h1>"
        f"<span class='sev {sev}'>{sev}</span> "
        f"<span class='muted'>{_esc(finding.get('internal_class'))} · "
        f"{_esc(finding.get('validation_state'))}</span>"
        f"<h2>Summary</h2><p>{_esc(finding.get('summary'))}</p>"
        f"<h2>Technical description</h2><pre>{_esc(finding.get('technical_description'))}</pre>"
        f"<h2>Steps to reproduce</h2>{repro or '<p class=muted>No reproduction captured.</p>'}"
        f"<h2>Evidence</h2><table><tr><th>Type</th><th>SHA-256</th><th>URI</th></tr>{ev_rows}</table>"
        f"<h2>Capability produced</h2><p>{_esc(', '.join(finding.get('capability_labels', []) or ['none']))}</p>"
        f"<h2>Standards</h2><p class='muted'>CWE-639, CWE-284 · OWASP API1:2023 BOLA</p>"
        f"<p><button data-export>Export HTML</button></p>"
    )
    return _shell(finding.get("title", "Finding"), body)


def attack_chain_html(chain: dict, steps: list[dict] | None = None,
                      capabilities: list[dict] | None = None) -> str:
    sev = _esc(chain.get("chain_severity", "informational"))
    step_rows = "".join(
        f"<tr><td>{_esc(s.get('sequence_number'))}</td>"
        f"<td>{_esc(s.get('finding_id'))}</td>"
        f"<td>{_esc(', '.join(s.get('resulting_capability_ids', [])))}</td>"
        f"<td>{_esc(s.get('validation_state'))}</td></tr>"
        for s in (steps or [])
    )
    rationale = chain.get("chain_scoring_rationale", {}) or {}
    body = (
        f"<h1>{_esc(chain.get('title'))}</h1>"
        f"<span class='sev {sev}'>{sev}</span> "
        f"<span class='muted'>chain severity (ArsGoatia method v"
        f"{_esc(rationale.get('method_version', '1.0.0'))}, not CVSS)</span>"
        f"<h2>Objective</h2><p>{_esc(chain.get('objective'))}</p>"
        f"<h2>Validated steps</h2><table>"
        f"<tr><th>#</th><th>Finding</th><th>Capabilities gained</th><th>State</th></tr>"
        f"{step_rows}</table>"
        f"<h2>Blast radius</h2><pre>{_esc(rationale)}</pre>"
        f"<h2>Recommended cut points</h2>"
        f"<p>Enforce object-level authorization on the affected endpoint; the chain "
        f"cannot form without the read_foreign_object capability.</p>"
        f"<p><button data-export>Export HTML</button></p>"
    )
    return _shell(chain.get("title", "Attack chain"), body)
