"""Q-007 — an effect must belong to an engine that EXISTS.

The defect, MEASURED before any of this was written: `engine_descriptor.conflicts()` returned six rows
and ALL SIX were generated by `weak_password_reset`, which had no executor on any surface. It was the
only one of 13 `EFFECTS` entries with a non-empty `invalidates`, so the whole negative half of the
planner's model — the Sussman half, the reason `effect_search` is a search and not a graph walk — was
generated by an engine that does not exist. A second entry, `soft_deleted_login`, had the same shape
with `establishes: ["authenticated"]`.

THE NEGATIVE CONTROLS COME FIRST IN THIS FILE, DELIBERATELY, and they were run first as probes before
the fix was applied. This codebase has shipped a guard that checks a declaration instead of a fact
eight times, and this ticket is one of them coming home: the standing recommendation was to
"set `solver_only=True` (the field exists)" and the field exists on 0 of 88 records. So every
clean-sheet assertion below is preceded by a test proving the same apparatus reports a dirty one.
"""
import copy

import engine_descriptor as ed
import tools as TL


# The EFFECTS table exactly as it stood at HEAD 2142c92 — both phantoms present, no `engine` key.
HISTORICAL_2026_08_17 = {
    "sqli_auth_bypass":      {"establishes": ["authenticated"], "invalidates": []},
    "default_credentials":   {"establishes": ["authenticated"], "invalidates": []},
    "jwt_forge":             {"establishes": ["authenticated"], "invalidates": []},
    "jwt_key_confusion":     {"establishes": ["authenticated"], "invalidates": []},
    "soft_deleted_login":    {"establishes": ["authenticated"], "invalidates": []},
    "saml_signature_bypass": {"establishes": ["authenticated"], "invalidates": []},
    "weak_password_reset":   {"establishes": ["authenticated"], "invalidates": ["authenticated"]},
    "sqli_union_extract":    {"establishes": ["credentials_exposed"], "invalidates": []},
    "exposed_files_harvest": {"establishes": ["credentials_exposed"], "invalidates": []},
    "target_intel_harvest":  {"establishes": ["credentials_exposed"], "invalidates": []},
    "graphql_introspection": {"establishes": ["has_api", "has_object_id"], "invalidates": []},
    "browser_persona_bola":  {"establishes": ["has_object_id", "authenticated"], "invalidates": []},
    "sqli_structural":       {"establishes": ["sql_error_seen"], "invalidates": []},
}

# MEASURED 2026-08-17. `routes()` derives engines from `ALWAYS_ON` prose and `wstg_catalog.FULL`, and
# `FULL["WSTG-INPV-05"]` is "run_sqli / run_auth_sqli" while THREE techniques carry that id — so the
# derivation hands `sqli_structural` the family pair while its real engine is the more precise
# `run_sqli_structural`. The declaration is the better answer here, so this disagreement is REPORTED
# rather than failed. Pinned as an exact set: a declaration pointed at the wrong engine grows this list
# and fails, and fixing the coarse WSTG entry shrinks it and also fails until recorded.
DIFFERS_FROM_DERIVED_2026_08_17 = [
    "sqli_structural: declared ['run_sqli_structural'] vs derived ['run_auth_sqli', 'run_sqli']",
]


# ── NEGATIVE CONTROLS ───────────────────────────────────────────────────────────────────────────

def test_the_guard_fails_on_the_table_it_was_written_to_catch():
    """The one that matters. Run the guard against the REAL pre-fix table and it must reject it, naming
    both phantoms. If this ever passes, the guard has stopped seeing the defect it exists for."""
    a = ed.effects_audit(effects=HISTORICAL_2026_08_17)
    assert a["ok"] is False
    assert "weak_password_reset" in a["no_engine_declared"]
    assert "soft_deleted_login" in a["no_engine_declared"]
    assert a["checked"] == 13


def test_the_guard_fails_on_an_invented_engine_name():
    """The mutation. Re-arm the phantom and give it the name it would have had if anyone had built it."""
    mut = copy.deepcopy(ed.EFFECTS)
    mut["weak_password_reset"] = {"establishes": ["authenticated"],
                                  "invalidates": ["authenticated"],
                                  "engine": ["run_weak_password_reset"]}
    a = ed.effects_audit(effects=mut)
    assert a["ok"] is False
    assert a["unregistered"] == ["weak_password_reset -> run_weak_password_reset"]
    assert a["unimplemented"] == ["weak_password_reset -> run_weak_password_reset"]


def test_a_phantom_engine_also_fails_the_routing_audit(monkeypatch):
    """Two independent nets, not one. `routing_audit()` scans the same declaration by MEMBERSHIP (not by
    the `run_|confirm_` shape filter it uses on prose, so a typo like `defualt_creds` cannot slip
    through), and its `phantom` list is already the load-bearing invariant the platform ships."""
    armed = copy.deepcopy(ed.EFFECTS)
    armed["weak_password_reset"] = {"establishes": ["authenticated"], "invalidates": ["authenticated"],
                                    "engine": ["run_weak_password_reset"]}
    monkeypatch.setattr(ed, "EFFECTS", armed)
    a = ed.routing_audit()
    assert a["ok"] is False
    assert a["phantom"] == ["weak_password_reset (effect_engine) -> run_weak_password_reset"]

    misspelled = copy.deepcopy(ed.EFFECTS)
    misspelled["default_credentials"] = dict(misspelled["default_credentials"],
                                             engine=["defualt_creds"])
    monkeypatch.setattr(ed, "EFFECTS", misspelled)
    a = ed.routing_audit()
    assert a["ok"] is False, "a non-engine-shaped typo slipped through the membership check"


def test_the_guard_fails_when_a_declared_engine_is_registered_but_not_implemented():
    """Registration and implementation are two different facts and this checks both. MEASURED today,
    `TOOL_PERMISSIONS - implementations` is EMPTY, so this cannot fire on a real registered name — the
    control therefore synthesises the divergence rather than pretending the tree contains one."""
    assert not (set(TL.TOOL_PERMISSIONS) - ed.engine_implementations()), \
        "a registered name lost its implementation; re-measure before editing this test"
    a = ed.effects_audit(implementations=ed.engine_implementations() - {"run_jwt"})
    assert a["ok"] is False
    assert a["unregistered"] == [], "the registry half must be unaffected"
    assert a["unimplemented"] == ["jwt_forge -> run_jwt", "jwt_key_confusion -> run_jwt"]


def test_the_guard_fails_closed_when_a_fact_table_cannot_be_read():
    """An instrument that loaded nothing must never report a clean sheet."""
    assert ed.effects_audit(registry=set())["ok"] is False
    assert ed.effects_audit(implementations=set())["ok"] is False


def test_the_guard_is_not_vacuous():
    """A scan over an empty set passes for free, which is the defect, not the fix."""
    empty = ed.effects_audit(effects={})
    assert empty["ok"] is False
    assert empty["checked"] == 0
    live = ed.effects_audit()
    assert live["checked"] >= 11
    assert live["registry_size"] > 100
    assert live["implementations_size"] > 100
    assert live["cross_checked_against_derived_route"] >= 9, \
        "no declaration was compared against an independently derived route"


# ── THE SHIPPED TREE ────────────────────────────────────────────────────────────────────────────

def test_the_shipped_effects_table_is_clean():
    a = ed.effects_audit()
    assert a["ok"] is True, a
    assert a["no_engine_declared"] == []
    assert a["unregistered"] == []
    assert a["unimplemented"] == []
    # every entry resolved to at least one engine that is BOTH registered and implemented
    assert set(a["verified"]) == set(ed.EFFECTS)
    assert all(v for v in a["verified"].values()), a["verified"]


def test_the_derived_route_disagreement_is_pinned():
    """The ratchet. SHRINK THIS LIST, NEVER GROW IT."""
    assert ed.effects_audit()["differs_from_derived_route"] == DIFFERS_FROM_DERIVED_2026_08_17


def test_the_two_phantoms_are_gone_from_the_effects_model_and_only_from_it():
    """The fix, stated as an invariant rather than a diff.

    Both keep their PRECONDITIONS entry deliberately. MEASURED: dropping `weak_password_reset` from
    `PRECONDITIONS` makes `technique_planner.orchestration_audit()` report
    `islands: ['weak_password_reset']`, because a precondition is the ORCHESTRATION claim (what gates
    this technique) and not the EXECUTOR claim (what runs it). Q-007 is about the second one. The first
    is Q-020's, and `routing_audit()["unrouted"]` is where the missing executor is already recorded."""
    for tid in ("weak_password_reset", "soft_deleted_login"):
        assert tid not in ed.EFFECTS
        assert tid in ed.PRECONDITIONS
        assert tid in ed.routing_audit()["unrouted"]


def test_every_row_the_planner_can_emit_names_a_dispatchable_engine():
    """The invariant the whole ticket reduces to: an engine in a chain or a conflict must be one the
    executor can actually run. NON-VACUITY is asserted on both halves SEPARATELY, because for one
    cycle `conflicts()` was legitimately empty and the conflict half of this loop ran zero times.

    Q-074 filled it from a measurement -- `run_race`, raced against a credential-rotation form with
    the mission's own session, took the scan's `GET /api/me` from (200, True) to (401, False), while
    `session_lifecycle` (the engine the ticket named) was driven against the shipped lab and changed
    no engagement state at all. The reasoning and the raw probe output live in
    docs/handoff/effects2.md and in tests/test_effects_negative_half.py."""
    d = ed.build()
    ch, cf = ed.chains(d), ed.conflicts(d)
    assert len(ch) > 40, "the chain walk found nothing; this test is not looking at anything"
    assert cf, "the conflict walk found nothing; the second half of this loop is not looking"
    for pid, obs, cid in ch + cf:
        assert d[pid]["engines"], "%s produces %s for %s with no engine" % (pid, obs, cid)
        assert all(e in TL.TOOL_PERMISSIONS for e in d[pid]["engines"]), pid
    assert {p for p, _o, _c in cf} == {"race_condition"}, \
        "a second negative effect shipped; it needs a measurement before it is pinned here"
