"""Security value generated by a DISCLOSED non-cryptographic PRNG (CWE-330 + CWE-209).

This is a narrow detector and it is worth being honest about why. Applications do not normally announce
which API they called. When one does -- through a stack trace, a debug banner, a verbose error page, or
a diagnostic build left enabled -- the disclosure is itself a finding (CWE-209), and if the API it names
is a non-cryptographic PRNG used to mint a token, cookie or identifier, then the weak-randomness finding
follows directly from the app's own statement about itself.

So the claim is deliberately modest: we are not inferring the algorithm from output shape, and we are
not proving predictability. We report exactly what the application disclosed, and only when it is tied
to a value that matters for security.

Two gates, both required, because either alone is noise:
  1. the response NAMES a weak generator, and does not name a strong one for the same operation;
  2. the response ties it to a SECURITY-SENSITIVE value -- a cookie, token, session or identifier.

Prose about randomness confirms nothing. A strong generator confirms nothing. A weak generator used for
something with no security meaning (a page nonce for cache-busting, an animation seed) confirms nothing.
"""
from __future__ import annotations

import re

# Non-cryptographic generators across the runtimes we meet. These are seeded PRNGs whose output is
# predictable from observed values; none is acceptable for a token, session id or secret.
_WEAK = [
    (r"java\.util\.Random(?:\.\w+)?\s*\(", "java.util.Random"),
    (r"java\.lang\.Math\.random\s*\(", "java.lang.Math.random"),
    (r"\bMath\.random\s*\(\s*\)", "Math.random"),
    (r"\brandom\.(?:random|randint|choice|randrange|uniform|getrandbits)\s*\(", "python random module"),
    (r"\bmt_rand\s*\(", "PHP mt_rand"),
    (r"(?<!s)\brand\s*\(\s*\)", "rand()"),
    (r"\bnp\.random\.", "numpy.random"),
]
# Cryptographically secure counterparts. Their presence for the same operation means the app is doing
# the right thing and the finding must be withheld.
_STRONG = re.compile(
    r"(SecureRandom|SystemRandom|secrets\.[a-z_]+\s*\(|crypto\.randomBytes|random_bytes\s*\(|"
    r"getrandom\s*\(|CryptGenRandom|RNGCryptoServiceProvider|os\.urandom)", re.I)
# The value has to matter. A predictable animation seed is not a vulnerability.
_SECURITY_CONTEXT = re.compile(
    r"(cookie|token|session|nonce|csrf|api[_-]?key|secret|password[_-]?reset|"
    r"remember[_-]?me|auth|identifier|\buuid\b|\bguid\b)", re.I)
_MAX = 400_000          # do not scan a payload-sized body for this


def disclosed_generator(body: str):
    """The weak generator the response names, or None. Strong generators suppress the match."""
    text = str(body or "")
    if not text or len(text) > _MAX:
        return None
    if _STRONG.search(text):
        return None
    for pattern, label in _WEAK:
        m = re.search(pattern, text)
        if m:
            return {"api": label, "quote": m.group(0)[:80]}
    return None


def evaluate(body: str) -> dict:
    """Confirmed only when a weak generator is disclosed AND bound to a security-sensitive value."""
    hit = disclosed_generator(body)
    if not hit:
        return {"confirmed": False, "oracle": ""}
    ctx = _SECURITY_CONTEXT.search(str(body or ""))
    if not ctx:
        # Disclosure without security meaning: real information leakage, but not weak randomness.
        return {"confirmed": False, "oracle": "", "note": "weak generator disclosed, no security context"}
    return {"confirmed": True, "api": hit["api"], "context": ctx.group(0).lower(),
            "oracle": ("the response itself discloses that %s -- a non-cryptographic generator -- was "
                       "used, and names a %s in the same response. The application is stating that a "
                       "security-relevant value comes from a predictable source; no inference from "
                       "output shape was required."
                       % (hit["api"], ctx.group(0).lower()))}


def finding(url: str, api: str, oracle: str) -> dict:
    return {
        "title": "Security value from a disclosed non-cryptographic PRNG (%s)" % api,
        "severity": "medium", "family": "weak_random", "confidence": "confirmed", "target": url,
        "cwe": "CWE-330", "cvss_vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N", "cvss_score": 5.9,
        "evidence": oracle,
        "success_oracle": oracle,
        "reproduction_steps": [
            "Request %s and read the response body." % url,
            "The response names %s, a non-cryptographic generator, alongside a security-relevant value."
            % api,
            "Collect successive values: a seeded PRNG is predictable once enough output is observed.",
        ],
        "impact": ("A token, session id or secret produced by a seeded PRNG is predictable. An attacker "
                   "who observes a handful of values can recover the generator state and derive past and "
                   "future values, enabling session hijacking or password-reset abuse. The disclosure "
                   "itself (CWE-209) is what makes this observable without source access."),
        "remediation": ("Generate security-relevant values with a cryptographically secure source "
                        "(SecureRandom, secrets, os.urandom, crypto.randomBytes). Separately, stop "
                        "returning internal API names, stack traces or debug banners to clients."),
        "tags": ["cwe-330", "cwe-209", "prng", "information-disclosure"],
    }
