# Temporal dynamic config for local development.
# Permissive limits suitable for a single-node dev cluster.
frontend.enableClientVersionCheck:
  - value: true
    constraints: {}
system.forceSearchAttributesCacheRefreshOnRead:
  - value: true
    constraints: {}
limit.maxIDLength:
  - value: 255
    constraints: {}
system.enableEagerWorkflowStart:
  - value: true
    constraints: {}
